[project]
name = "note-book"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "notebook>=7.4.5",
]

[dependency-groups]
dev = [
    "ruff>=0.12.8",
]
